### ISSUE TITLE
ImportError: No module named 'RDN'

### ISSUE THREAD

**Issue by OhniMik** [DevKiHyun/RDN-Tensorflow#1]
/RDN-Tensorflow의 경로에서 python3 main.py를 실행시키면

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import RDN.rdn as rdn
ImportError: No module named 'RDN'
와 같은 오류가 발생합니다 ㅠㅠ

현재 파일의 경로는

RDN-Tensorflow/
total 80
drwxr-xr-x 7 root root  4096 Sep  7 15:23 ./
drwxr-xr-x 3 root root  4096 Sep  7 14:06 ../
drwxr-xr-x 5 root root  4096 Sep  7 13:29 data/
-rwxr-xr-x 1 root root  3947 Sep  7 13:29 demo.py*
drwxr-xr-x 8 root root  4096 Sep  7 13:29 .git/
-rw-r--r-- 1 root root    66 Sep  7 13:29 .gitattributes
-rwxr-xr-x 1 root root  1078 Sep  7 15:18 main.py*
-rw-r--r-- 1 root root 12288 Sep  7 15:24 .main.py.swp
drwxr-xr-x 3 root root  4096 Sep  7 13:29 model/
drwxr-xr-x 2 root root  4096 Sep  7 13:42 __pycache__/
-rwxr-xr-x 1 root root  6117 Sep  7 13:29 rdn.py*
-rwxr-xr-x 1 root root  1450 Sep  7 13:29 README.md*
drwxr-xr-x 2 root root  4096 Sep  7 13:29 result/
-rwxr-xr-x 1 root root  7501 Sep  7 13:29 train.py*
-rwxr-xr-x 1 root root  7675 Sep  7 13:29 util.py*

/RDN-Tensorflow/data
total 44
drwxr-xr-x 5 root root 4096 Sep  7 13:29 ./
drwxr-xr-x 7 root root 4096 Sep  7 15:23 ../
-rwxr-xr-x 1 root root 3287 Sep  7 13:29 aug_test.m*
-rwxr-xr-x 1 root root 6011 Sep  7 13:29 aug_train.m*
drwxr-xr-x 3 root root 4096 Sep  7 13:29 B100/
-rwxr-xr-x 1 root root 1746 Sep  7 13:29 preprocess.py*
-rwxr-xr-x 1 root root  901 Sep  7 13:29 random_extract.py*
-rwxr-xr-x 1 root root   89 Sep  7 13:29 README.md*
drwxr-xr-x 3 root root 4096 Sep  7 13:29 Set5/
drwxr-xr-x 3 root root 4096 Sep  7 13:29 Urban100/

와 같습니다

**Comment by DevKiHyun** [comment]
이 코드들은 반드시 'RDN'이라는 이름의 메인 디렉토리 안에서 동작해야 됩니다. 따라서 메인 디렉토리의 이름은 'RDN' 이여야 합니다. 이를 해결하기 위해 메인 디렉토리를 추가하였습니다.

-------------------------------------------------------------------------------------------------------------------
These codes must execute in a main directory named 'RDN'. So, the main directory's name must be 'RDN' . I added the main directory named 'RDN' to solve this problem.
